# Generated by Django 4.2.7 on 2023-12-29 18:15

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
    ]
