# Generated by Django 4.2.7 on 2024-01-03 03:57

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('bot_core', '0002_collection_embedding_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=4096),
        ),
    ]
