# Generated by Django 4.2.7 on 2023-11-19 16:44

import django.contrib.postgres.fields
from django.db import migrations, models
import experiences.models.vocations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subskills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('level', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Vocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('WORK', 'work'), ('VOLU', 'volunteer'), ('NONP', 'non-profit')], default='WORK', max_length=4)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=experiences.models.vocations.rename_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(to='experiences.skill')),
            ],
            options={
                'verbose_name': 'Vocation',
                'verbose_name_plural': 'Vocations',
            },
        ),
    ]
